# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kristy James
email: "'.'.join('kristy', 'p', 'james') + '@gmail.com'"
description: > # this means to ignore newlines until "baseurl:"
  A growing website about interesting stuff I've been doing with
  electronic articulography, computational linguistics
  and other writings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kristyj.github.io" # the base hostname & protocol for your site
twitter_username: kristylein
github_username:  kristyj

# Build settings
markdown: kramdown
